{% set name = "tree-sitter-cli" %}
{% set version = "0.24.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tree-sitter/tree-sitter/archive/v{{ version }}.tar.gz
  sha256: 199da041ac7ef62bccdda9b7bec28aafa073f7eea2677680aa7992d503c9cc64

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - tree-sitter --help

about:
  home: https://github.com/tree-sitter/tree-sitter-cli
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: An incremental parsing system for programming tools
  dev_url: https://github.com/tree-sitter/tree-sitter-cli

extra:
  recipe-maintainers:
    - danielnachun
