context:
  version: "0.25.3"

package:
  name: tree-sitter-cli
  version: ${{ version }}

source:
  url: https://github.com/tree-sitter/tree-sitter/archive/v${{ version }}.tar.gz
  sha256: 862fac52653bc7bc9d2cd0630483e6bdf3d02bcd23da956ca32663c4798a93e3

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - tree-sitter --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: An incremental parsing system for programming tools
  homepage: https://github.com/tree-sitter/tree-sitter-cli
  repository: https://github.com/tree-sitter/tree-sitter-cli

extra:
  recipe-maintainers:
    - danielnachun
